version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    # ports:
    #   - "3000:3000"  # Map the container port to the host port (host:container)

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    # ports:
    #   - "8080:80"  # Map the container port to the host port (host:container)

  nginx:
    image: nginx:latest
    ports:
      - "8888:80"  # Map the Nginx container port to the host port (host:container)
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
